using System;
using System.IO;
using System.Reflection;
using System.Security.Cryptography;

namespace UtilityPDF.Security
{
    /// <summary>
    /// Verifies the integrity and authenticity of downloaded binaries
    /// using SHA-256 hash and RSA-4096 digital signature.
    /// </summary>
    internal static class BinaryIntegrityVerifier
    {
        /// <summary>
        /// RSA-4096 public key in XML format.
        /// Loaded from embedded resource (auto-generated by generate-signing-keys.ps1).
        /// The corresponding private key is kept ONLY in CI/CD secrets.
        /// </summary>
        private static readonly string PublicKeyXml = LoadPublicKeyXml();

        /// <summary>
        /// Loads the RSA public key XML from the embedded resource.
        /// </summary>
        private static string LoadPublicKeyXml()
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            using Stream stream = assembly.GetManifestResourceStream("UtilityPDF.Security.PublicKeyXml") ?? throw new InvalidOperationException(
                    "Embedded resource 'UtilityPDF.Security.PublicKeyXml' not found. " +
                    "Run scripts/generate-signing-keys.ps1 and rebuild.");
            using StreamReader reader = new StreamReader(stream);
            return reader.ReadToEnd().Trim();
        }

        /// <summary>
        /// Verifies that a file matches the expected SHA-256 hash
        /// </summary>
        /// <param name="filePath">Path to the file to verify</param>
        /// <param name="expectedHashHex">Expected SHA-256 hash in hex format</param>
        /// <returns>True if hash matches</returns>
        public static bool VerifySha256Hash(string filePath, string expectedHashHex)
        {
            if (string.IsNullOrWhiteSpace(filePath) || !File.Exists(filePath))
            {
                return false;
            }

            if (string.IsNullOrWhiteSpace(expectedHashHex))
            {
                return false;
            }

            try
            {
                using SHA256 sha256 = SHA256.Create();
                using FileStream stream = File.OpenRead(filePath);
                byte[] hashBytes = sha256.ComputeHash(stream);
                string computedHash = BitConverter.ToString(hashBytes).Replace("-", "").ToLowerInvariant();
                string expected = expectedHashHex.Trim().ToLowerInvariant();

                // Constant-time comparison to prevent timing attacks
                return ConstantTimeEquals(computedHash, expected);
            }
            catch (Exception)
            {
                return false;
            }
        }

        /// <summary>
        /// Verifies the RSA-4096 signature of a file using the embedded public key
        /// </summary>
        /// <param name="filePath">Path to the file that was signed</param>
        /// <param name="signatureBytes">Raw RSA signature bytes</param>
        /// <returns>True if signature is valid</returns>
        public static bool VerifySignature(string filePath, byte[] signatureBytes)
        {
            if (string.IsNullOrWhiteSpace(filePath) || !File.Exists(filePath))
            {
                return false;
            }

            if (signatureBytes == null || signatureBytes.Length == 0)
            {
                return false;
            }

            try
            {
                using RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
                rsa.FromXmlString(PublicKeyXml);

                byte[] fileBytes = File.ReadAllBytes(filePath);

                // Verify signature using SHA-256 hash algorithm
                return rsa.VerifyData(fileBytes, SHA256.Create(), signatureBytes);
            }
            catch (CryptographicException)
            {
                return false;
            }
            catch (Exception)
            {
                return false;
            }
        }

        /// <summary>
        /// Performs full integrity verification: SHA-256 hash + RSA signature
        /// </summary>
        /// <param name="filePath">Path to the binary to verify</param>
        /// <param name="expectedHashHex">Expected SHA-256 hash (hex string)</param>
        /// <param name="signatureBase64">RSA signature in Base64 encoding</param>
        /// <returns>Verification result with detailed status</returns>
        public static IntegrityResult VerifyFull(string filePath, string expectedHashHex, string signatureBase64)
        {
            IntegrityResult result = new IntegrityResult();

            // Step 1: Verify SHA-256 hash
            if (!VerifySha256Hash(filePath, expectedHashHex))
            {
                result.ErrorMessage = "SHA-256 hash mismatch — file may be corrupted or tampered";
                return result;
            }

            result.HashValid = true;

            // Step 2: Verify RSA signature
            try
            {
                byte[] signatureBytes = Convert.FromBase64String(signatureBase64);

                if (!VerifySignature(filePath, signatureBytes))
                {
                    result.ErrorMessage = "RSA signature verification failed — file is not authentic";
                    return result;
                }

                result.SignatureValid = true;
            }
            catch (FormatException)
            {
                result.ErrorMessage = "Invalid signature format (not valid Base64)";
                return result;
            }

            return result;
        }

        /// <summary>
        /// Constant-time string comparison to prevent timing attacks
        /// </summary>
        private static bool ConstantTimeEquals(string a, string b)
        {
            if (a.Length != b.Length)
            {
                return false;
            }

            int result = 0;
            for (int i = 0; i < a.Length; i++)
            {
                result |= a[i] ^ b[i];
            }

            return result == 0;
        }
    }
}
