//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPDF.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilityPDF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string CompressCompleted {
            get {
                return ResourceManager.GetString("CompressCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maximum Quality (Prepress).
        /// </summary>
        internal static string CompressLvl_0 {
            get {
                return ResourceManager.GetString("CompressLvl_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a High Quality (Printer).
        /// </summary>
        internal static string CompressLvl_1 {
            get {
                return ResourceManager.GetString("CompressLvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Medium Quality (eBook).
        /// </summary>
        internal static string CompressLvl_2 {
            get {
                return ResourceManager.GetString("CompressLvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Low Quality (Screen).
        /// </summary>
        internal static string CompressLvl_3 {
            get {
                return ResourceManager.GetString("CompressLvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configuration not initialized. Call Initialize() first..
        /// </summary>
        internal static string ConfigNotInit {
            get {
                return ResourceManager.GetString("ConfigNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string ConvertCompleted {
            get {
                return ResourceManager.GetString("ConvertCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select output directory for compressed PDF....
        /// </summary>
        internal static string DirectoryOutputCompressedPDF {
            get {
                return ResourceManager.GetString("DirectoryOutputCompressedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to create log directory due to insufficient permissions.\nLogging will be disabled.\n\nAttempted locations:\n1. {0}\n2. {1}.
        /// </summary>
        internal static string ErrorCreateLogDir {
            get {
                return ResourceManager.GetString("ErrorCreateLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logging Error.
        /// </summary>
        internal static string ErrorCreateLogDirTitle {
            get {
                return ResourceManager.GetString("ErrorCreateLogDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No settings to save..
        /// </summary>
        internal static string ErrorSettingsSave {
            get {
                return ResourceManager.GetString("ErrorSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to create log directory in application folder.\nLogs will be saved to:\n{0}.
        /// </summary>
        internal static string FallbackLogDir {
            get {
                return ResourceManager.GetString("FallbackLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log Directory Notification.
        /// </summary>
        internal static string FallbackLogDirTitle {
            get {
                return ResourceManager.GetString("FallbackLogDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred:.
        /// </summary>
        internal static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress PDF.
        /// </summary>
        internal static string HeaderCompressPDF {
            get {
                return ResourceManager.GetString("HeaderCompressPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert to DOCX/RTF.
        /// </summary>
        internal static string HeaderConvertPDF {
            get {
                return ResourceManager.GetString("HeaderConvertPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract Text (OCR).
        /// </summary>
        internal static string HeaderExtractText {
            get {
                return ResourceManager.GetString("HeaderExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge PDFs.
        /// </summary>
        internal static string HeaderMergePDFs {
            get {
                return ResourceManager.GetString("HeaderMergePDFs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extraction &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string InfoCompleteExtraction {
            get {
                return ResourceManager.GetString("InfoCompleteExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compression in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblCompressInProgress {
            get {
                return ResourceManager.GetString("LblCompressInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compression Level:.
        /// </summary>
        internal static string LblCompressionLvl {
            get {
                return ResourceManager.GetString("LblCompressionLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conversion in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblConvertInProgress {
            get {
                return ResourceManager.GetString("LblConvertInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language UI.
        /// </summary>
        internal static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblMergeInProgress {
            get {
                return ResourceManager.GetString("LblMergeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF file to DOCX/RTF CONVERT.
        /// </summary>
        internal static string LblMsgInputPDF_Conv {
            get {
                return ResourceManager.GetString("LblMsgInputPDF_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF file from EXTRACT TEXT.
        /// </summary>
        internal static string LblMsgInputPDF_Extr {
            get {
                return ResourceManager.GetString("LblMsgInputPDF_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output DOCX/RTF.
        /// </summary>
        internal static string LblMsgOutputDIR_Conv {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output TXT File.
        /// </summary>
        internal static string LblMsgOutputDIR_Extr {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output Merged PDF.
        /// </summary>
        internal static string LblMsgOutputDIR_Merge {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select OCR Language:.
        /// </summary>
        internal static string LblMsgSelLang {
            get {
                return ResourceManager.GetString("LblMsgSelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress PDF.
        /// </summary>
        internal static string LblPanelCompress {
            get {
                return ResourceManager.GetString("LblPanelCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert to DOCX/RTF.
        /// </summary>
        internal static string LblPanelConvDOCX {
            get {
                return ResourceManager.GetString("LblPanelConvDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract Text (OCR).
        /// </summary>
        internal static string LblPanelExtract {
            get {
                return ResourceManager.GetString("LblPanelExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge PDFs.
        /// </summary>
        internal static string LblPanelMerge {
            get {
                return ResourceManager.GetString("LblPanelMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ApplicationShutdown.
        /// </summary>
        internal static string Log_ApplicationShutdown {
            get {
                return ResourceManager.GetString("Log_ApplicationShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ApplicationStartup.
        /// </summary>
        internal static string Log_ApplicationStartup {
            get {
                return ResourceManager.GetString("Log_ApplicationStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CloseReason.
        /// </summary>
        internal static string Log_CloseReason {
            get {
                return ResourceManager.GetString("Log_CloseReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completed.
        /// </summary>
        internal static string Log_Completed {
            get {
                return ResourceManager.GetString("Log_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CompressionLevel.
        /// </summary>
        internal static string Log_CompressionLevel {
            get {
                return ResourceManager.GetString("Log_CompressionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configuration Error.
        /// </summary>
        internal static string Log_ConfigError {
            get {
                return ResourceManager.GetString("Log_ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during configuration initialization:\n{0}.
        /// </summary>
        internal static string Log_ConfigErrorTitle {
            get {
                return ResourceManager.GetString("Log_ConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language CSV file not found: {0}.
        /// </summary>
        internal static string Log_CsvNotFound {
            get {
                return ResourceManager.GetString("Log_CsvNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory.
        /// </summary>
        internal static string Log_Dir {
            get {
                return ResourceManager.GetString("Log_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ErrorType.
        /// </summary>
        internal static string Log_ErrorType {
            get {
                return ResourceManager.GetString("Log_ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to enumerate traineddata files: {0}.
        /// </summary>
        internal static string Log_FailedTessData {
            get {
                return ResourceManager.GetString("Log_FailedTessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FileCount.
        /// </summary>
        internal static string Log_FileCount {
            get {
                return ResourceManager.GetString("Log_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FilePath.
        /// </summary>
        internal static string Log_FilePath {
            get {
                return ResourceManager.GetString("Log_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main form loading - initializing UI components.
        /// </summary>
        internal static string Log_InitializingUI {
            get {
                return ResourceManager.GetString("Log_InitializingUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO error in async operation: {0}.
        /// </summary>
        internal static string Log_IOErrorAsyncOp {
            get {
                return ResourceManager.GetString("Log_IOErrorAsyncOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO error during text extraction: {0}.
        /// </summary>
        internal static string Log_IOErrorTextExtr {
            get {
                return ResourceManager.GetString("Log_IOErrorTextExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logging disabled: No valid log directory available..
        /// </summary>
        internal static string Log_LogDisabled {
            get {
                return ResourceManager.GetString("Log_LogDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error initializing logging system: {0}.
        /// </summary>
        internal static string Log_LogErrInit {
            get {
                return ResourceManager.GetString("Log_LogErrInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Critical: Failed to write error log - {0}.
        /// </summary>
        internal static string Log_LogErrWrite {
            get {
                return ResourceManager.GetString("Log_LogErrWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MainFormClosing.
        /// </summary>
        internal static string Log_MainFormClosing {
            get {
                return ResourceManager.GetString("Log_MainFormClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MainFormLoad.
        /// </summary>
        internal static string Log_MainFormLoad {
            get {
                return ResourceManager.GetString("Log_MainFormLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Main form displayed and ready.
        /// </summary>
        internal static string Log_MainFormReady {
            get {
                return ResourceManager.GetString("Log_MainFormReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Found {0} traineddata files in {1}.
        /// </summary>
        internal static string Log_NumTessData {
            get {
                return ResourceManager.GetString("Log_NumTessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OcrLanguage.
        /// </summary>
        internal static string Log_OcrLanguage {
            get {
                return ResourceManager.GetString("Log_OcrLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OutputFormat.
        /// </summary>
        internal static string Log_OutputFormat {
            get {
                return ResourceManager.GetString("Log_OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OutputPath.
        /// </summary>
        internal static string Log_OutputPath {
            get {
                return ResourceManager.GetString("Log_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text extraction: {0} pages to process.
        /// </summary>
        internal static string Log_PageProcess {
            get {
                return ResourceManager.GetString("Log_PageProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PdfCompress.
        /// </summary>
        internal static string Log_PdfCompress {
            get {
                return ResourceManager.GetString("Log_PdfCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PdfConvert.
        /// </summary>
        internal static string Log_PdfConvert {
            get {
                return ResourceManager.GetString("Log_PdfConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PdfMerge.
        /// </summary>
        internal static string Log_PdfMerge {
            get {
                return ResourceManager.GetString("Log_PdfMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PdfPath.
        /// </summary>
        internal static string Log_PdfPath {
            get {
                return ResourceManager.GetString("Log_PdfPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Runtime.
        /// </summary>
        internal static string Log_Runtime {
            get {
                return ResourceManager.GetString("Log_Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shutdown blocked: an operation is still in progress.
        /// </summary>
        internal static string Log_ShutdownBlocked {
            get {
                return ResourceManager.GetString("Log_ShutdownBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source.
        /// </summary>
        internal static string Log_Source {
            get {
                return ResourceManager.GetString("Log_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Started.
        /// </summary>
        internal static string Log_Started {
            get {
                return ResourceManager.GetString("Log_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tesseract data directory not found: {0}.
        /// </summary>
        internal static string Log_TessDataDir {
            get {
                return ResourceManager.GetString("Log_TessDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TextExtraction.
        /// </summary>
        internal static string Log_TextExtraction {
            get {
                return ResourceManager.GetString("Log_TextExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TotalPages.
        /// </summary>
        internal static string Log_TotalPages {
            get {
                return ResourceManager.GetString("Log_TotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unexpected error in async operation: {0}.
        /// </summary>
        internal static string Log_UnexErrAsyncOp {
            get {
                return ResourceManager.GetString("Log_UnexErrAsyncOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unexpected error during text extraction: {0}.
        /// </summary>
        internal static string Log_UnexErrTextExt {
            get {
                return ResourceManager.GetString("Log_UnexErrTextExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unknown.
        /// </summary>
        internal static string Log_Unknown {
            get {
                return ResourceManager.GetString("Log_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version.
        /// </summary>
        internal static string Log_Version {
            get {
                return ResourceManager.GetString("Log_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to load language data: {0}.
        /// </summary>
        internal static string LogFailedLoadLang {
            get {
                return ResourceManager.GetString("LogFailedLoadLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loaded {0} language entries from CSV.
        /// </summary>
        internal static string LogNumLangCsv {
            get {
                return ResourceManager.GetString("LogNumLangCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string MsgBoxErrorTitle {
            get {
                return ResourceManager.GetString("MsgBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        internal static string MsgBoxInformationTitle {
            get {
                return ResourceManager.GetString("MsgBoxInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        internal static string MsgBoxWarningTitle {
            get {
                return ResourceManager.GetString("MsgBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select PDF file to compress....
        /// </summary>
        internal static string PDFFileToCOMPRESS {
            get {
                return ResourceManager.GetString("PDFFileToCOMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DOCX only.
        /// </summary>
        internal static string RdBtnOutFormat_0 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RTF only.
        /// </summary>
        internal static string RdBtnOutFormat_1 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DOCX and RTF.
        /// </summary>
        internal static string RdBtnOutFormat_2 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An IO error occurred:.
        /// </summary>
        internal static string SpecificMessageErrorIO {
            get {
                return ResourceManager.GetString("SpecificMessageErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abort.
        /// </summary>
        internal static string TxtAbortBtn {
            get {
                return ResourceManager.GetString("TxtAbortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress.
        /// </summary>
        internal static string TxtCompressBtn {
            get {
                return ResourceManager.GetString("TxtCompressBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert.
        /// </summary>
        internal static string TxtConvertBtn {
            get {
                return ResourceManager.GetString("TxtConvertBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        internal static string TxtExitBtn {
            get {
                return ResourceManager.GetString("TxtExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        internal static string TxtExtractBtn {
            get {
                return ResourceManager.GetString("TxtExtractBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge.
        /// </summary>
        internal static string TxtMergetBtn {
            get {
                return ResourceManager.GetString("TxtMergetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output.
        /// </summary>
        internal static string TxtOutputDirBtn {
            get {
                return ResourceManager.GetString("TxtOutputDirBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string TxtResetBtn {
            get {
                return ResourceManager.GetString("TxtResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select PDF.
        /// </summary>
        internal static string TxtSelectPDFBtn {
            get {
                return ResourceManager.GetString("TxtSelectPDFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extraction &gt;&gt;&gt; ABORTED &lt;&lt;&lt; !!!.
        /// </summary>
        internal static string WarnAbortedExtraction {
            get {
                return ResourceManager.GetString("WarnAbortedExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to abort the current operation?.
        /// </summary>
        internal static string WarnConfirmAbort {
            get {
                return ResourceManager.GetString("WarnConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (OUTPUT file will have the SAME NAME_COMPRESSED as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirCOMP {
            get {
                return ResourceManager.GetString("WarnSelectOutDirCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a DOCX/RTF file with the same name already exists (DOCX/RTF file will have the SAME NAME_CONVERT.DOCX/RTF as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirDOCX {
            get {
                return ResourceManager.GetString("WarnSelectOutDirDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (PDF_MERGED file will have the SAME NAME_MERGED as the first selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirMERGE {
            get {
                return ResourceManager.GetString("WarnSelectOutDirMERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a TXT file with the same name already exists (TXT file will have the SAME NAME.TXT as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirTXT {
            get {
                return ResourceManager.GetString("WarnSelectOutDirTXT", resourceCulture);
            }
        }
    }
}
