//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPDF.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilityPDF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string CompressCompleted {
            get {
                return ResourceManager.GetString("CompressCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maximum Quality (Prepress).
        /// </summary>
        internal static string CompressLvl_0 {
            get {
                return ResourceManager.GetString("CompressLvl_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a High Quality (Printer).
        /// </summary>
        internal static string CompressLvl_1 {
            get {
                return ResourceManager.GetString("CompressLvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Medium Quality (eBook).
        /// </summary>
        internal static string CompressLvl_2 {
            get {
                return ResourceManager.GetString("CompressLvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Low Quality (Screen).
        /// </summary>
        internal static string CompressLvl_3 {
            get {
                return ResourceManager.GetString("CompressLvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string ConvertCompleted {
            get {
                return ResourceManager.GetString("ConvertCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select output directory for compressed PDF....
        /// </summary>
        internal static string DirectoryOutputCompressedPDF {
            get {
                return ResourceManager.GetString("DirectoryOutputCompressedPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred:.
        /// </summary>
        internal static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extraction &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string InfoCompleteExtraction {
            get {
                return ResourceManager.GetString("InfoCompleteExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compression in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblCompressInProgress {
            get {
                return ResourceManager.GetString("LblCompressInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compression Level:.
        /// </summary>
        internal static string LblCompressionLvl {
            get {
                return ResourceManager.GetString("LblCompressionLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conversion in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblConvertInProgress {
            get {
                return ResourceManager.GetString("LblConvertInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language UI.
        /// </summary>
        internal static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge in progress...
        ///
        ///Please wait....
        /// </summary>
        internal static string LblMergeInProgress {
            get {
                return ResourceManager.GetString("LblMergeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF file to DOCX/RTF CONVERT.
        /// </summary>
        internal static string LblMsgInputPDF_Conv {
            get {
                return ResourceManager.GetString("LblMsgInputPDF_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF file from EXTRACT TEXT.
        /// </summary>
        internal static string LblMsgInputPDF_Extr {
            get {
                return ResourceManager.GetString("LblMsgInputPDF_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output DOCX/RTF.
        /// </summary>
        internal static string LblMsgOutputDIR_Conv {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output TXT File.
        /// </summary>
        internal static string LblMsgOutputDIR_Extr {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output Merged PDF.
        /// </summary>
        internal static string LblMsgOutputDIR_Merge {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select OCR Language:.
        /// </summary>
        internal static string LblMsgSelLang {
            get {
                return ResourceManager.GetString("LblMsgSelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress PDF.
        /// </summary>
        internal static string LblPanelCompress {
            get {
                return ResourceManager.GetString("LblPanelCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert to DOCX/RTF.
        /// </summary>
        internal static string LblPanelConvDOCX {
            get {
                return ResourceManager.GetString("LblPanelConvDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract Text (OCR).
        /// </summary>
        internal static string LblPanelExtract {
            get {
                return ResourceManager.GetString("LblPanelExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge PDFs.
        /// </summary>
        internal static string LblPanelMerge {
            get {
                return ResourceManager.GetString("LblPanelMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string MsgBoxErrorTitle {
            get {
                return ResourceManager.GetString("MsgBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        internal static string MsgBoxInformationTitle {
            get {
                return ResourceManager.GetString("MsgBoxInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        internal static string MsgBoxWarningTitle {
            get {
                return ResourceManager.GetString("MsgBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select PDF file to compress....
        /// </summary>
        internal static string PDFFileToCOMPRESS {
            get {
                return ResourceManager.GetString("PDFFileToCOMPRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DOCX only.
        /// </summary>
        internal static string RdBtnOutFormat_0 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RTF only.
        /// </summary>
        internal static string RdBtnOutFormat_1 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DOCX and RTF.
        /// </summary>
        internal static string RdBtnOutFormat_2 {
            get {
                return ResourceManager.GetString("RdBtnOutFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An IO error occurred:.
        /// </summary>
        internal static string SpecificMessageErrorIO {
            get {
                return ResourceManager.GetString("SpecificMessageErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abort.
        /// </summary>
        internal static string TxtAbortBtn {
            get {
                return ResourceManager.GetString("TxtAbortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress.
        /// </summary>
        internal static string TxtCompressBtn {
            get {
                return ResourceManager.GetString("TxtCompressBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert.
        /// </summary>
        internal static string TxtConvertBtn {
            get {
                return ResourceManager.GetString("TxtConvertBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        internal static string TxtExitBtn {
            get {
                return ResourceManager.GetString("TxtExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        internal static string TxtExtractBtn {
            get {
                return ResourceManager.GetString("TxtExtractBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge.
        /// </summary>
        internal static string TxtMergetBtn {
            get {
                return ResourceManager.GetString("TxtMergetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output.
        /// </summary>
        internal static string TxtOutputDirBtn {
            get {
                return ResourceManager.GetString("TxtOutputDirBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string TxtResetBtn {
            get {
                return ResourceManager.GetString("TxtResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select PDF.
        /// </summary>
        internal static string TxtSelectPDFBtn {
            get {
                return ResourceManager.GetString("TxtSelectPDFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extraction &gt;&gt;&gt; ABORTED &lt;&lt;&lt; !!!.
        /// </summary>
        internal static string WarnAbortedExtraction {
            get {
                return ResourceManager.GetString("WarnAbortedExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to abort the current operation?.
        /// </summary>
        internal static string WarnConfirmAbort {
            get {
                return ResourceManager.GetString("WarnConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (OUTPUT file will have the SAME NAME_COMPRESSED as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirCOMP {
            get {
                return ResourceManager.GetString("WarnSelectOutDirCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a DOCX/RTF file with the same name already exists (DOCX/RTF file will have the SAME NAME_CONVERT.DOCX/RTF as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirDOCX {
            get {
                return ResourceManager.GetString("WarnSelectOutDirDOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (PDF_MERGED file will have the SAME NAME_MERGED as the first selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirMERGE {
            get {
                return ResourceManager.GetString("WarnSelectOutDirMERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a TXT file with the same name already exists (TXT file will have the SAME NAME.TXT as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirTXT {
            get {
                return ResourceManager.GetString("WarnSelectOutDirTXT", resourceCulture);
            }
        }
    }
}
