//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilityPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string CompressCompleted {
            get {
                return ResourceManager.GetString("CompressCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VERY LOW COMPRESS --&gt; MAX QUALITY.
        /// </summary>
        internal static string CompressLvl_0 {
            get {
                return ResourceManager.GetString("CompressLvl_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LOW COMPRESS --&gt; HIGH QUALITY.
        /// </summary>
        internal static string CompressLvl_1 {
            get {
                return ResourceManager.GetString("CompressLvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MEDIUM COMPRESS --&gt; MEDIUM QUALITY.
        /// </summary>
        internal static string CompressLvl_2 {
            get {
                return ResourceManager.GetString("CompressLvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HIGH COMPRESS --&gt; LOW QUALITY.
        /// </summary>
        internal static string CompressLvl_3 {
            get {
                return ResourceManager.GetString("CompressLvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert &gt;&gt;&gt; ABORTED &lt;&lt;&lt; !!!.
        /// </summary>
        internal static string ConvertAborted {
            get {
                return ResourceManager.GetString("ConvertAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string ConvertCompleted {
            get {
                return ResourceManager.GetString("ConvertCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error occurred: .
        /// </summary>
        internal static string GenericMessageError {
            get {
                return ResourceManager.GetString("GenericMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress PDF in progress....
        /// </summary>
        internal static string LblCompressInProgress {
            get {
                return ResourceManager.GetString("LblCompressInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compression LEVEL.
        /// </summary>
        internal static string LblCompressionLvl {
            get {
                return ResourceManager.GetString("LblCompressionLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge PDF in progress....
        /// </summary>
        internal static string LblMergeInProgress {
            get {
                return ResourceManager.GetString("LblMergeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF file from EXTRACT TEXT.
        /// </summary>
        internal static string LblMsgInputPDF_Extr {
            get {
                return ResourceManager.GetString("LblMsgInputPDF_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output TXT File.
        /// </summary>
        internal static string LblMsgOutputDIR_Extr {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Extr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory Output Merged PDF.
        /// </summary>
        internal static string LblMsgOutputDIR_Merge {
            get {
                return ResourceManager.GetString("LblMsgOutputDIR_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select the language that OCR should use for extraction.
        /// </summary>
        internal static string LblMsgSelLang {
            get {
                return ResourceManager.GetString("LblMsgSelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress PDF.
        /// </summary>
        internal static string LblPanelCompress {
            get {
                return ResourceManager.GetString("LblPanelCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract Text From PDF Using OCR.
        /// </summary>
        internal static string LblPanelExtract {
            get {
                return ResourceManager.GetString("LblPanelExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge PDF.
        /// </summary>
        internal static string LblPanelMerge {
            get {
                return ResourceManager.GetString("LblPanelMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge &gt;&gt;&gt; COMPLETED &lt;&lt;&lt;.
        /// </summary>
        internal static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PDFUti {
            get {
                object obj = ResourceManager.GetObject("PDFUti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An IO error occurred: .
        /// </summary>
        internal static string SpecificMessageErrorIO {
            get {
                return ResourceManager.GetString("SpecificMessageErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abort.
        /// </summary>
        internal static string TxtAbortBtn {
            get {
                return ResourceManager.GetString("TxtAbortBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Compress.
        /// </summary>
        internal static string TxtCompressBtn {
            get {
                return ResourceManager.GetString("TxtCompressBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exit.
        /// </summary>
        internal static string TxtExitBtn {
            get {
                return ResourceManager.GetString("TxtExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extract.
        /// </summary>
        internal static string TxtExtractBtn {
            get {
                return ResourceManager.GetString("TxtExtractBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merge.
        /// </summary>
        internal static string TxtMergetBtn {
            get {
                return ResourceManager.GetString("TxtMergetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select DIR .
        /// </summary>
        internal static string TxtOutputDirBtn {
            get {
                return ResourceManager.GetString("TxtOutputDirBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string TxtResetBtn {
            get {
                return ResourceManager.GetString("TxtResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select PDF.
        /// </summary>
        internal static string TxtSelectPDFBtn {
            get {
                return ResourceManager.GetString("TxtSelectPDFBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you confirm extraction &gt;&gt;&gt; ABORT &lt;&lt;&lt; ?.
        /// </summary>
        internal static string WarnConfirmAbort {
            get {
                return ResourceManager.GetString("WarnConfirmAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (OUTPUT file will have the SAME NAME_COMPRESSED as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirCOMP {
            get {
                return ResourceManager.GetString("WarnSelectOutDirCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a PDF file with the same name already exists (PDF_MERGED file will have the SAME NAME + MERGED as the first selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirMERGE {
            get {
                return ResourceManager.GetString("WarnSelectOutDirMERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If a TXT file with the same name already exists (TXT file will have the SAME NAME as the selected PDF file) in the folder you select, it will be overwritten!!!.
        /// </summary>
        internal static string WarnSelectOutDirTXT {
            get {
                return ResourceManager.GetString("WarnSelectOutDirTXT", resourceCulture);
            }
        }
    }
}
