# =============================================================================
# Generate RSA-4096 signing key pair for UtilityPDF auto-update
#
# Run this ONCE to create:
#   - update-signing-key.pem      : Private key (KEEP SECRET — CI/CD only)
#   - update-signing-key.pub.pem  : Public key (for verification)
#   - update-signing-key.pub.der  : Public key DER (for C++ BCrypt import)
#   - update-signing-key.pub.xml  : Public key XML (for C# RSACryptoServiceProvider)
#   - PublicKeyBytes.h            : C++ header with embedded DER bytes
#                                   (auto-copped to UpdaterBootstrap.Native\src\)
#
# SECURITY:
#   - NEVER commit the .pem private key to Git
#   - Store it ONLY in GitHub Secrets (SIGNING_PRIVATE_KEY)
#   - The public key files CAN be committed
#
# Requires: OpenSSL (available in Git for Windows)
# =============================================================================

param(
    [Parameter(Mandatory=$false)]
    [string]$OutputDir = "keys",

    [Parameter(Mandatory=$false)]
    [int]$KeySize = 4096
)

$ErrorActionPreference = "Stop"

# Check OpenSSL
$openssl = Get-Command "openssl" -ErrorAction SilentlyContinue
if (-not $openssl) {
    $gitOpenssl = "C:\Program Files\Git\usr\bin\openssl.exe"
    if (Test-Path $gitOpenssl) {
        $openssl = $gitOpenssl
    } else {
        Write-Error "OpenSSL not found. Install OpenSSL or Git for Windows."
        exit 1
    }
} else {
    $openssl = $openssl.Source
}

# Create output directory
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$privatePem = Join-Path $OutputDir "update-signing-key.pem"
$publicPem = Join-Path $OutputDir "update-signing-key.pub.pem"
$publicDer = Join-Path $OutputDir "update-signing-key.pub.der"
$publicXml = Join-Path $OutputDir "update-signing-key.pub.xml"
$cppHeader = Join-Path $OutputDir "PublicKeyBytes.h"
$cppHeaderDest = "UpdaterBootstrap.Native\src\PublicKeyBytes.h"
$xmlKeyDest = "UtilityPDF\Security\update-signing-key.pub.xml"

Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "  RSA-$KeySize Key Pair Generator" -ForegroundColor Cyan
Write-Host "  Output: $OutputDir" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: Generate RSA private key ---
Write-Host "[1/7] Generating RSA-$KeySize private key..." -ForegroundColor Yellow
$ErrorActionPreference = "Continue"
& $openssl genrsa -out $privatePem $KeySize 2>&1 | Out-Null
$ErrorActionPreference = "Stop"
if ($LASTEXITCODE -ne 0) { Write-Error "Failed to generate private key"; exit 1 }
Write-Host "  Private key: $privatePem" -ForegroundColor Green

# --- Step 2: Extract public key (PEM) ---
Write-Host "[2/7] Extracting public key (PEM)..." -ForegroundColor Yellow
$ErrorActionPreference = "Continue"
& $openssl rsa -in $privatePem -pubout -out $publicPem 2>&1 | Out-Null
$ErrorActionPreference = "Stop"
if ($LASTEXITCODE -ne 0) { Write-Error "Failed to extract public key PEM"; exit 1 }
Write-Host "  Public key PEM: $publicPem" -ForegroundColor Green

# --- Step 3: Export public key (DER) for C++ BCrypt ---
Write-Host "[3/7] Exporting public key (DER) for C++..." -ForegroundColor Yellow
$ErrorActionPreference = "Continue"
& $openssl rsa -in $privatePem -pubout -outform DER -out $publicDer 2>&1 | Out-Null
$ErrorActionPreference = "Stop"
if ($LASTEXITCODE -ne 0) { Write-Error "Failed to export public key DER"; exit 1 }
Write-Host "  Public key DER: $publicDer" -ForegroundColor Green

# --- Step 4: Generate C++ header with DER bytes ---
Write-Host "[4/7] Generating C++ header (PublicKeyBytes.h)..." -ForegroundColor Yellow

$derBytes = [System.IO.File]::ReadAllBytes($publicDer)
$lines = @()
$lines += "#pragma once"
$lines += ""
$lines += "// RSA-$KeySize Public Key (DER-encoded SubjectPublicKeyInfo)"
$lines += "// Generated by generate-signing-keys.ps1"
$lines += "// Included by UpdateValidator.cpp for archive signature verification"
$lines += ""
$lines += "static const unsigned char kPublicKeyDer[] = {"

$hexLines = @()
for ($i = 0; $i -lt $derBytes.Length; $i += 16) {
    $chunk = $derBytes[$i..([Math]::Min($i + 15, $derBytes.Length - 1))]
    $hexValues = ($chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "

    if ($i + 16 -lt $derBytes.Length) {
        $hexLines += "    $hexValues,"
    } else {
        $hexLines += "    $hexValues"
    }
}

$lines += $hexLines
$lines += "};"
$lines += ""
$lines += "static const size_t kPublicKeyDerSize = sizeof(kPublicKeyDer);"
$lines += ""

$lines | Out-File -FilePath $cppHeader -Encoding UTF8
Write-Host "  C++ header: $cppHeader ($($derBytes.Length) bytes)" -ForegroundColor Green

# --- Step 5: Copy PublicKeyBytes.h to UpdaterBootstrap.Native\src\ ---
Write-Host "[5/7] Copying PublicKeyBytes.h to C++ project source..." -ForegroundColor Yellow
if (Test-Path (Split-Path $cppHeaderDest)) {
    Copy-Item -Path $cppHeader -Destination $cppHeaderDest -Force
    Write-Host "  Copied to: $cppHeaderDest" -ForegroundColor Green
} else {
    Write-Host "  WARNING: Directory $(Split-Path $cppHeaderDest) not found, skipping copy." -ForegroundColor DarkYellow
    Write-Host "  Manually copy $cppHeader to your project src\ folder." -ForegroundColor DarkYellow
}

# --- Step 6: Generate XML for C# RSACryptoServiceProvider ---
Write-Host "[6/7] Generating XML for C#..." -ForegroundColor Yellow

# Extract modulus and exponent using OpenSSL
$ErrorActionPreference = "Continue"
$rsaText = & $openssl rsa -in $privatePem -text -noout 2>&1
$ErrorActionPreference = "Stop"

# Parse modulus
$modulusHex = ""
$inModulus = $false
foreach ($line in $rsaText -split "`n") {
    $trimmed = $line.Trim()
    if ($trimmed -match "^modulus:") {
        $inModulus = $true
        continue
    }
    if ($inModulus) {
        if ($trimmed -match "^[0-9a-f:]+$") {
            $modulusHex += $trimmed.Replace(":", "")
        } else {
            $inModulus = $false
        }
    }
}

# Remove leading 00 if present (ASN.1 padding)
if ($modulusHex.StartsWith("00")) {
    $modulusHex = $modulusHex.Substring(2)
}

# Convert hex to Base64
$modulusBytes = [byte[]]::new($modulusHex.Length / 2)
for ($i = 0; $i -lt $modulusBytes.Length; $i++) {
    $modulusBytes[$i] = [Convert]::ToByte($modulusHex.Substring($i * 2, 2), 16)
}
$modulusBase64 = [Convert]::ToBase64String($modulusBytes)
$exponentBase64 = "AQAB" # 65537

$xml = "<RSAKeyValue><Modulus>$modulusBase64</Modulus><Exponent>$exponentBase64</Exponent></RSAKeyValue>"
$xml | Out-File -FilePath $publicXml -Encoding UTF8 -NoNewline
Write-Host "  XML for C#: $publicXml" -ForegroundColor Green

# --- Step 7: Copy XML public key to UtilityPDF\Security\ (Embedded Resource) ---
Write-Host "[7/7] Copying XML public key to C# project..." -ForegroundColor Yellow
if (Test-Path (Split-Path $xmlKeyDest)) {
    Copy-Item -Path $publicXml -Destination $xmlKeyDest -Force
    Write-Host "  Copied to: $xmlKeyDest" -ForegroundColor Green
    Write-Host "  (Embedded Resource - loaded at runtime by BinaryIntegrityVerifier)" -ForegroundColor DarkGray
} else {
    Write-Host "  WARNING: Directory $(Split-Path $xmlKeyDest) not found, skipping copy." -ForegroundColor DarkYellow
    Write-Host "  Manually copy $publicXml to UtilityPDF\Security\ folder." -ForegroundColor DarkYellow
}

# --- Summary ---
Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  KEY GENERATION COMPLETE" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Files generated:" -ForegroundColor White
Write-Host "    PRIVATE (SECRET): $privatePem" -ForegroundColor Red
Write-Host "    Public PEM:       $publicPem" -ForegroundColor White
Write-Host "    Public DER:       $publicDer" -ForegroundColor White
Write-Host "    C++ header:       $cppHeader -> $cppHeaderDest" -ForegroundColor White
Write-Host "    C# XML:           $publicXml -> $xmlKeyDest" -ForegroundColor White
Write-Host ""
Write-Host "  AUTO-DEPLOYED:" -ForegroundColor Cyan
Write-Host "    C++ #include:     $cppHeaderDest" -ForegroundColor Green
Write-Host "    C# Embedded Res:  $xmlKeyDest" -ForegroundColor Green
Write-Host ""
Write-Host "  NEXT STEPS:" -ForegroundColor Cyan
Write-Host "  1. Ensure $xmlKeyDest is set as Embedded Resource in .csproj" -ForegroundColor White
Write-Host "     (already configured if .csproj was updated)" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  2. Store private key in GitHub Secrets:" -ForegroundColor White
Write-Host "     Secret name: SIGNING_PRIVATE_KEY" -ForegroundColor DarkGray
Write-Host "     Value: contents of $privatePem" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  3. Add to .gitignore:" -ForegroundColor White
Write-Host "     keys/update-signing-key.pem" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  SECURITY WARNING:" -ForegroundColor Red
Write-Host "  NEVER commit the private key (.pem) to Git!" -ForegroundColor Red
Write-Host ""
